version: '3'
services:
  spring-usecase-web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:10.0-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
volumes:
  pg_data: